### PR TITLE
Add clang format file

### PR DESCRIPTION
**Pull request by renzenicolai**
This adds the .clang-format file I use in most of my projects

### CODE REVIEW

**Comment by Orange-Murker** [comment]
Would it make more sense to keep consistent formatting between the firmware repository and the components? The firmware already has a .clang-format file that differs from yours

**Comment by renzenicolai** [comment]
> Would it make more sense to keep consistent formatting between the firmware repository and the components? The firmware already has a .clang-format file that differs from yours

Good point, I will take a look at the .clang-format from the firmware repository. Would it be okay if I merged the two or is the preference to keep the .clang-format from the firmware repository as-is?

**Comment by Orange-Murker** [comment]
> > Would it make more sense to keep consistent formatting between the firmware repository and the components? The firmware already has a .clang-format file that differs from yours
> 
> Good point, I will take a look at the .clang-format from the firmware repository. Would it be okay if I merged the two or is the preference to keep the .clang-format from the firmware repository as-is?

I prefer to just use the version from the firmware repository here

**Comment by renzenicolai** [comment]
@Orange-Murker Updated, the PR now contains the .clang-format file from the p4 firmware repo.

Note that the file hasn't been applied yet, I will do that in a separate PR after my other PRs have been merged.

**Review by Orange-Murker — APPROVED** [review]

**Pull request merged**
